class_data_dir: class_img/backpack
class_prompt: a photo of backpack
instance_data_dir: dataset/backpack
instance_prompt: a photo of sks backpack
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/backpack
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
