class_data_dir: class_img/bowl
class_prompt: a photo of bowl
instance_data_dir: dataset/berry_bowl
instance_prompt: a photo of sks bowl
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/berry_bowl
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
