class_data_dir: class_img/can
class_prompt: a photo of can
instance_data_dir: dataset/can
instance_prompt: a photo of sks can
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/can
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
