class_data_dir: class_img/candle
class_prompt: a photo of candle
instance_data_dir: dataset/candle
instance_prompt: a photo of sks candle
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/candle
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
