class_data_dir: class_img/cat
class_prompt: a photo of cat
instance_data_dir: dataset/cat
instance_prompt: a photo of sks cat
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/cat
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
