class_data_dir: class_img/boot
class_prompt: a photo of boot
instance_data_dir: dataset/fancy_boot
instance_prompt: a photo of sks boot
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/fancy_boot
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
