class_data_dir: class_img/glasses
class_prompt: a photo of glasses
instance_data_dir: dataset/pink_sunglasses
instance_prompt: a photo of sks glasses
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/pink_sunglasses
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
