class_data_dir: class_img/toy
class_prompt: a photo of toy
instance_data_dir: dataset/rc_car
instance_prompt: a photo of sks toy
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/rc_car
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
