class_data_dir: class_img/sneaker
class_prompt: a photo of sneaker
instance_data_dir: dataset/shiny_sneaker
instance_prompt: a photo of sks sneaker
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/shiny_sneaker
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
