class_data_dir: class_img/teapot
class_prompt: a photo of teapot
instance_data_dir: dataset/teapot
instance_prompt: a photo of sks teapot
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/teapot
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
