class_data_dir: class_img/vase
class_prompt: a photo of vase
instance_data_dir: dataset/vase
instance_prompt: a photo of sks vase
learning_rate: 0.0001
max_train_steps: 800
output_dir: eval_weights/vase
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
train_batch_size: 1
