adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
allow_tf32: false
alphaedit_knowledge_dir: knowledge_base
alphaedit_samples: 2000
alphaedit_threshold: 1e-4
center_crop: false
checkpointing_steps: 500
class_data_dir: class_img/stuffed animal
class_prompt: a photo of stuffed animal
enable_xformers_memory_efficient_attention: false
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: null
hub_token: null
instance_data_dir: dataset/wolf_plushie
instance_prompt: a photo of sks stuffed animal
learning_rate: 0.0001
local_rank: -1
logging_dir: logs
lora_alpha: 27
lora_bias: none
lora_dropout: 0.0
lora_r: 16
lora_text_encoder_alpha: 17
lora_text_encoder_bias: none
lora_text_encoder_dropout: 0.0
lora_text_encoder_r: 16
lr_num_cycles: 1
lr_power: 1.0
lr_scheduler: constant
lr_warmup_steps: 0
max_grad_norm: 1.0
max_train_steps: 800
mixed_precision: null
no_tracemalloc: false
num_class_images: 200
num_dataloader_workers: 1
num_train_epochs: 1
num_validation_images: 4
output_dir: eval_weights/wolf_plushie
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
prior_generation_precision: null
prior_loss_weight: 1.0
push_to_hub: false
report_to: tensorboard
resolution: 512
resume_from_checkpoint: null
revision: null
sample_batch_size: 4
scale_lr: false
seed: null
tokenizer_name: null
train_batch_size: 1
train_text_encoder: true
use_8bit_adam: false
use_alphaedit: true
use_lora: true
validation_prompt: null
validation_steps: 100
wandb_key: null
wandb_project_name: null
with_prior_preservation: true
