revision: null  
tokenizer_name: null
with_prior_preservation: false  
prior_loss_weight: 1.0  
num_class_images: 200  
validation_prompt: null  
num_validation_images: 4  
validation_steps: 100  
seed: null  
resolution: 512  
center_crop: false  
train_text_encoder: true  

# AlphaEdit相关设置
use_alphaedit: false
alphaedit_knowledge_dir: null
alphaedit_samples: 1000
alphaedit_threshold: 1e-5
alphaedit_strict_protection: false

use_lora: false  
lora_r: 16  
lora_alpha: 27  
lora_dropout: 0.0  
lora_bias: "none"  
lora_text_encoder_r: 16  
lora_text_encoder_alpha: 17  
lora_text_encoder_dropout: 0.0  
lora_text_encoder_bias: "none"  

num_dataloader_workers: 16
no_tracemalloc: false  
train_batch_size: 1  
sample_batch_size: 4  
num_train_epochs: 1  
max_train_steps: 400
checkpointing_steps: 500  
resume_from_checkpoint: null  
gradient_accumulation_steps: 1  
gradient_checkpointing: true  
learning_rate: 1.0e-4  
scale_lr: false  
lr_scheduler: "constant"  
lr_warmup_steps: 0  
lr_num_cycles: 1  
lr_power: 1.0  
use_8bit_adam: false  
adam_beta1: 0.9  
adam_beta2: 0.999  
adam_weight_decay: 0.01  
adam_epsilon: 1.0e-8  
max_grad_norm: 1.0  
push_to_hub: false  
hub_token: null  
hub_model_id: null  
logging_dir: "logs"  
allow_tf32: false  
report_to: "tensorboard"  
wandb_key: null  
wandb_project_name: null  
mixed_precision: null  
prior_generation_precision: null  
local_rank: -1  
enable_xformers_memory_efficient_attention: false  
